[tool.poetry]
name = "fastapi-tortoise-async-test-demo"
version = "0.1.0"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
fastapi = {version="^0.115.2", extras=["standard"]}
tortoise-orm = "^0.21.7"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.1"
fastapi-cdn-host = "^0.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
mypy = "^1.12.0"
ruff = "^0.6.9"
asgi-lifespan = "^2.1.0"
httpx = "^0.27.2"
coverage = [
    {version="^7.6.3", python="^3.9"},
    {version="7.6.1", python="3.8"}
]
typer = "^0.12.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
pretty = true
ignore_missing_imports = true
check_untyped_defs = true

[tool.coverage.report]
omit = ["*/tests/*"]
exclude_lines = [
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:",
]
