[tool.poetry]
name = "fastapi-tortoise-async-test-demo"
version = "0.1.0"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.78.0"
tortoise-orm = "^0.19.1"
httpx = "^0.23.0"
asyncpg = "^0.25.0"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
