[tool.poetry]
name = "fastapi-tortoise-async-test-demo"
version = "0.1.0"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.110.1"
tortoise-orm = "^0.20.0"
httpx = "^0.27.0"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.1"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
fastapi-cdn-host = "^0.4.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
starlette = "*"
pydantic = "*"
coverage = "^7.4.4"
click = "*"
h11 = "*"
pydantic-core = "*"
annotated-types = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
