[tool.poetry]
name = "fastapi-tortoise-async-test-demo"
version = "0.1.0"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.111.0"
tortoise-orm = "^0.21.3"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.1"
fastapi-cdn-host = "^0.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
coverage = "^7.5.3"
mypy = "^1.10.0"
ruff = "^0.4.9"
asgi-lifespan = "^2.1.0"
httpx = {git="ssh://git@github.com/encode/httpx"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
pretty = true
ignore_missing_imports = true
check_untyped_defs = true

[tool.coverage.report]
omit = ["*/tests/*"]
exclude_lines = [
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:",
]
