[tool.poetry]
name = "fastapi-tortoise-async-test-demo"
version = "0.1.0"
description = ""
authors = ["Waket Zheng <waketzheng@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.110.2"
tortoise-orm = {git = "https://github.com/tortoise/tortoise-orm.git"}
httpx = "^0.27.0"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.1"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
fastapi-cdn-host = "^0.4.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
coverage = "^7.5.0"
click = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true
